#!/bin/bash

case "$BLOCK_BUTTON" in
	1) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle;;
	4) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+;;
	5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-;;
esac

volume_frac="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d' ' -f2)"
volume="$(echo "$volume_frac * 100 / 1" | bc)%"

if [ -z "$volume" ]; then
    exit 1
fi

if  wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q "[MUTED]"; then
    icon=""
else
    icon=$volume
fi

echo "$icon"
